version: '3.8'

services:
  web:
    container_name: container_web_django
    build:
      context: ./
    volumes:
      - .:/app
    ports:
      - "8081:80"
    env_file:
      - .env
    environment:
      - DATABASE_HOST=postgres
    command: sh -c "sleep 10; until nc -z postgres 5432; do sleep 1; done; python manage.py runserver 0.0.0.0:80"

  postgres:
    container_name: container_postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
